// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnUpzp-EZg6JAsQ7_puB8uKwL1opmf5CM',
    appId: '1:878980289676:web:69c718bccb00d74deb17a9',
    messagingSenderId: '878980289676',
    projectId: 'lesbase-e4e7f',
    authDomain: 'lesbase-e4e7f.firebaseapp.com',
    storageBucket: 'lesbase-e4e7f.appspot.com',
    measurementId: 'G-2K67NGQ2ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsH2yFr50L6IRQOcn5xAb8k5plUhSnMfQ',
    appId: '1:878980289676:android:7de4690dd23e2f99eb17a9',
    messagingSenderId: '878980289676',
    projectId: 'lesbase-e4e7f',
    storageBucket: 'lesbase-e4e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZHQibs058tC8kDMDD0PesYkCRsrT0Bo',
    appId: '1:878980289676:ios:218ca793d371cde5eb17a9',
    messagingSenderId: '878980289676',
    projectId: 'lesbase-e4e7f',
    storageBucket: 'lesbase-e4e7f.appspot.com',
    iosBundleId: 'com.example.filezy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ZHQibs058tC8kDMDD0PesYkCRsrT0Bo',
    appId: '1:878980289676:ios:218ca793d371cde5eb17a9',
    messagingSenderId: '878980289676',
    projectId: 'lesbase-e4e7f',
    storageBucket: 'lesbase-e4e7f.appspot.com',
    iosBundleId: 'com.example.filezy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnUpzp-EZg6JAsQ7_puB8uKwL1opmf5CM',
    appId: '1:878980289676:web:e6733f5ee724a5cbeb17a9',
    messagingSenderId: '878980289676',
    projectId: 'lesbase-e4e7f',
    authDomain: 'lesbase-e4e7f.firebaseapp.com',
    storageBucket: 'lesbase-e4e7f.appspot.com',
    measurementId: 'G-3MVF28SQZL',
  );
}